# add ondelete cascade for tasks.user_id
# Revision ID: d73b05133a4c
# Revises: 8da653f101f6
# Create Date: 2026-02-15 06:21:21.929625
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73b05133a4c'
down_revision: Union[str, Sequence[str], None] = '8da653f101f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
